AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront Distribution for EHR Frontend (HTTPS Support)'

Resources:
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: 'EHR AI System Frontend Distribution'
        DefaultRootObject: 'index.html'
        
        # Origin Configuration - S3 Website Endpoint
        Origins:
          - Id: S3-EHR-Frontend
            DomainName: 'ehr-frontend-48208.s3-website-us-east-1.amazonaws.com'
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: 'http-only'
              OriginSSLProtocols:
                - 'TLSv1.2'
        
        # Default Cache Behavior
        DefaultCacheBehavior:
          TargetOriginId: S3-EHR-Frontend
          ViewerProtocolPolicy: 'redirect-to-https'  # Force HTTPS
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: 'none'
          MinTTL: 0
          DefaultTTL: 86400  # 1 day
          MaxTTL: 31536000   # 1 year
        
        # Custom Error Responses (for SPA routing)
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: '/index.html'
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: '/index.html'
            ErrorCachingMinTTL: 300
        
        # Price Class (cheaper option)
        PriceClass: 'PriceClass_100'  # North America & Europe only
        
        # HTTP Version
        HttpVersion: 'http2'
        
        # IPv6
        IPV6Enabled: true

Outputs:
  CloudFrontURL:
    Description: 'CloudFront Distribution HTTPS URL'
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontURL'
  
  CloudFrontDistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'
